/* eslint-disable */

import { type NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';

const Home: NextPage = () => {
  const [usersByAPIrouter, setUsersByAPIrouter] = useState<any[]>([]);
  const [usersByClient, setUsersByClient] = useState<any[]>([]);
  const fetchUsers = async () => {
    const [_usersByApi, _usersByClient] = await Promise.all([
      (async () => {
        const res = (await (
          await fetch('https://jsonplaceholder.typicode.com/users/')
        ).json()) as any[];
        setUsersByClient(res);
      })(),
      (async () => {
        const res = (await (await fetch('/api/users')).json()) as {
          users: any[];
        };
        setUsersByAPIrouter(res.users);
      })(),
    ]);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ display: 'flex', flexDirection: 'row' }}>
        <button onClick={fetchUsers}>取得</button>
        <ul>
          クライアント
          {usersByClient.map((user) => (
            <li key={(user as any).id}>{(user as any).name}</li>
          ))}
        </ul>
        <ul>
          APIルーター
          {usersByAPIrouter.map((user) => (
            <li key={(user as any).id}>{(user as any).name}</li>
          ))}
        </ul>
      </div>
    </>
  );
};

export default Home;
