/* eslint-disable */

import { type NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';

const Home: NextPage = () => {
  const [users, setUsers] = useState([]);
  const fetchUsers = async () => {
    const response = await fetch('/api/users');
    const data = await response.json();
    setUsers(data.users);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        <button onClick={fetchUsers}>取得</button>
        {users.map((user) => (
          <li key={(user as any).id}>{(user as any).name}</li>
        ))}
      </ul>
    </>
  );
};

export default Home;
